fix(streamer): added streamer pagination
dymensionxyz/dymension pull request #1100
Opened 2024-08-13 18:29 UTC by keruch

## Description

Added streamer pagination. ADR: https://www.notion.so/dymension/ADR-x-Streamer-Pagination-ad21ef72458e472cad9fb6f9932c16cd.

- Added a `BeforeEpochStart` hook
- Modified a `AfterEpochEnd` hook
- Added `EndBlock`
- Now rewards are distributed not in a single block, but along the whole epoch
- Added stream iterator

Please pay special attention to 
- [StreamIterator](https://github.com/dymensionxyz/dymension/blob/kirill/1010-streamer-pagination/x/streamer/keeper/stream_iterator.go)
- [Epoch hooks](https://github.com/dymensionxyz/dymension/blob/kirill/1010-streamer-pagination/x/streamer/keeper/hooks.go)
- [EndBlock](https://github.com/dymensionxyz/dymension/blob/kirill/1010-streamer-pagination/x/streamer/keeper/abci.go)

----

Closes #1010

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [x]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x]  Targeted PR against the correct branch
- [x]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x]  Linked to the GitHub issue with discussion and accepted design
- [x]  Targets only one GitHub issue
- [x]  Wrote unit and integration tests
- [x]  Wrote relevant migration scripts if necessary
- [x]  All CI checks have passed
- [x]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [x]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [x] Registered Invariants
- [x] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map` <- only in one place and under my supervision
- [x] No usage of `time.Now()`
- [x] Used fixed point arithmetic and not float arithmetic
- [x] Avoid panicking in Begin/End block as much as possible
- [x] No unexpected math Overflow
- [x] Used `sendCoin` and not `SendCoins`
- [x] Out-of-block compute is bounded
- [x] No serialized ID at the end of store keys
- [x] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

----

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

2024-08-22 09:37 UTC, mtsitrin commented on x/streamer/keeper/hooks.go
> +func (k Keeper) BeforeEpochStart(ctx sdk.Context, epochIdentifier string) error {
add documantation

2024-08-22 09:37 UTC, mtsitrin commented on x/streamer/keeper/hooks.go
> +func (k Keeper) AfterEpochEnd(ctx sdk.Context, epochIdentifier string) (sdk.Coins, error) {
add documantation

2024-08-22 09:37 UTC, mtsitrin commented on x/streamer/keeper/distribute.go
> +	// Check if stream has completed its distribution
why u check it on `EpochStart` and not on after the distribution phase?

2024-08-22 09:37 UTC, mtsitrin commented on x/streamer/keeper/hooks.go
>  	}
lets wrap it in `k.GetActiveStreamsForEpoch(ctx, epochIdentifier)`, as it's used above as well

2024-08-22 09:37 UTC, mtsitrin commented on x/streamer/keeper/keeper.go
> +	if !pointerExists {
can set on genesis with the avaialble `epochs`, as the epoch list is immutable
than u can assume `EpochPointer` exists for all epochs

2024-08-22 09:37 UTC, mtsitrin commented on x/streamer/keeper/abci.go
> +	for _, p := range epochPointers {
is it sorted? I guess it make more sense to start with the short epochs (e.g min before day)

2024-08-24 14:54 UTC, zale144 requested changes
nice work. left some comments

2024-08-24 14:54 UTC, zale144 commented on x/streamer/keeper/abci.go
> +	err = ctx.EventManager().EmitTypedEvent(&types.EventEndBlock{
```suggestion
	err = uevent.EmitTypedEvent(ctx, &types.EventEndBlock{
```

2024-08-24 14:54 UTC, zale144 commented on x/streamer/keeper/distribute.go
> +	// TODO: can we delete this event?
if we don't end up deleting it, please use `uevent.EmitTypedEvent` as suggested above

2024-08-24 14:54 UTC, zale144 commented on x/streamer/keeper/hooks.go
> +	err := ctx.EventManager().EmitTypedEvent(&types.EventEpochStart{
use `uevent.EmitTypedEvent`

2024-08-24 14:54 UTC, zale144 commented on x/streamer/module.go
> +		panic(err)
yeah, do we really need to halt the chain here?

2024-08-30 15:37 UTC, omritoptix commented
@keruch build fails

2024-09-03 08:20 UTC, zale144 commented on internal/pagination/paginate.go
> +package pagination
shouldn't this be somewhere in utils or something?

2024-09-03 08:40 UTC, zale144 approved these changes
very nice

2024-09-03 19:09 UTC, mtsitrin commented on x/streamer/keeper/distribute.go
> +		stream.FilledEpochs += 1
it's possible for `stream.FilledEpochs = stream.NumEpochsPaidOver`, and thus will be considered `NotActive` for this method:

```
// IsActiveStream returns true if the stream is in an active state during the provided time.
func (stream Stream) IsActiveStream(curTime time.Time) bool {
	if (curTime.After(stream.StartTime) || curTime.Equal(stream.StartTime)) && (stream.FilledEpochs < stream.NumEpochsPaidOver) {
		return true
	}
	return false
}

```
wdyt?

2024-09-03 19:22 UTC, mtsitrin commented on x/streamer/keeper/distribute.go
>  		}
need `return pagination.Continue` in case of error?

2024-09-03 19:25 UTC, mtsitrin commented on x/streamer/keeper/distribute.go
> +		distributed, errX := k.DistributeToGauge(ctx, v.Stream.EpochCoins, v.Gauge, v.Stream.DistributeTo.TotalWeight)
don't it need to be in cache ctx?
semi-succefull `DistributeToGauge` should be reverted
otherwise the state can be some undesired state

2024-09-10 18:34 UTC, mtsitrin approved these changes

2024-09-10 18:34 UTC, merged