refactor(lightclient):  removed the need for next stateInfo for valiadition
dymensionxyz/dymension pull request #1467
Opened 2024-11-13 13:00 UTC by mtsitrin

* refactor ValidateUpdatePessimistically to use single state info
(instead of checking state info for H+1)

* refactor canonical client check - using iterator instead of getting **all** consensus states

2024-11-14 12:45 UTC, danwt requested changes
The cleanups are great, but the bit about iterating descending doesn't make sense.

https://github.com/dymensionxyz/dymension/blob/1deed9f69af08bac45d50514cf3d9ce5e1e4bff9/x/lightclient/keeper/canonical_client.go#L97-L125

You're only checking the consensus states with heights in the state info, which isn't right. I'm sorry I should've thought about it more when you initially asked me on slack.

Now it's not secure; why? Because there can be invalid consensus states below the ones you check, which are opening a security hole by having a wrong nextValidatorsHash.

We need to iterate through all the consensus states and check that they're valid. In fact, we just need to check that there is a valid _prefix_ . The reason it was implemented the way it was to begin with was because it's just simpler: if we check all up to and including the ones in the state info, then (in the previous design where a mismatch in state update would automatically trigger fraud handler) then we would be guaranteed to catch a wrong one.

I would really suggest to just keep it as it was before. You can still change it to be an iterator though (I think why Spoorthi made it fetch all before was because iterator was not publicly exposed). 

The rest of the PR is good

2024-11-14 12:45 UTC, danwt commented on x/lightclient/keeper/canonical_client.go
> +		if h.GetRevisionHeight() >= maxHeight {
>
```suggestion
		if h.GetRevisionHeight() > maxHeight {
```

2024-11-14 12:45 UTC, danwt commented on x/lightclient/keeper/canonical_client.go
>  	// for future state updates, which will incur a fraud if they disagree.)
This comment is no longer valid since you dont check against states less than the state info, and they wont be frauded

2024-11-14 12:45 UTC, danwt commented on x/lightclient/keeper/hook_listener.go
>  	}
```suggestion
			
		}
		
	}
```

Removing the `return nil` : makes sure people are not stuck with unbond restriction

Removing: prune signers below: it's called below too, so no need

2025-01-10 13:43 UTC, danwt approved these changes

2025-01-10 13:43 UTC, danwt commented on x/rollapp/types/state_info.go
> +
```suggestion
func (s *StateInfo) Successor(height uint64) string {
	if height != s.GetLatestHeight() {
		return s.Sequencer
	}
	return s.NextProposer
}

```

2025-01-10 13:43 UTC, danwt commented
Great job
Not from your PR but I'm not a fan of this mutable nextSequencer field on the state info

2025-01-13 11:00 UTC, mtsitrin commented
> Great job Not from your PR but I'm not a fan of this mutable nextSequencer field on the state info

agree
it was added for dymint validation process

2025-01-13 11:01 UTC, merged