Issue #562 fixes
dymensionxyz/dymension pull request #564
Opened 2024-02-12 13:55 UTC by muku314115

## Description

Refactoring sdkerrors throughout the project

----

Closes #562 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpeted math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

---

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

2024-02-14 08:08 UTC, mtsitrin requested changes
thanks for the contribution!
pls use consistent naming throughout the codebase
either
`errorsmod "cosmossdk.io/errors"`
or
`sdkerrors "cosmossdk.io/errors"`

2024-02-15 06:35 UTC, muku314115 commented
> thanks for the contribution! pls use consistent naming throughout the codebase either `errorsmod "cosmossdk.io/errors"` or `sdkerrors "cosmossdk.io/errors"`

thaks, I have used sdkerrors for all "cosmossdk.io/errors" and errortypes for all "github.com/cosmos/cosmos-sdk/types/errors"
is there any change required there?

2024-02-19 07:20 UTC, mtsitrin commented
> > thanks for the contribution! pls use consistent naming throughout the codebase either `errorsmod "cosmossdk.io/errors"` or `sdkerrors "cosmossdk.io/errors"`
> 
> thanks, I have used sdkerrors for all "cosmossdk.io/errors" and errortypes for all "github.com/cosmos/cosmos-sdk/types/errors" is there any change required there?

e.g https://github.com/dymensionxyz/dymension/blob/6bdc4bc5c12f6c774a8227e07423dc6167ecd4c1/app/ante/reject_msgs.go#L4

pls rename all to `sdkerrors "cosmossdk.io/errors"`

2024-02-20 06:23 UTC, muku314115 commented
> > > thanks for the contribution! pls use consistent naming throughout the codebase either `errorsmod "cosmossdk.io/errors"` or `sdkerrors "cosmossdk.io/errors"`
> > 
> > 
> > thanks, I have used sdkerrors for all "cosmossdk.io/errors" and errortypes for all "github.com/cosmos/cosmos-sdk/types/errors" is there any change required there?
> 
> e.g
> 
> https://github.com/dymensionxyz/dymension/blob/6bdc4bc5c12f6c774a8227e07423dc6167ecd4c1/app/ante/reject_msgs.go#L4
> 
> pls rename all to `sdkerrors "cosmossdk.io/errors"`

Thanks for letting me know, added the changes

2024-02-20 20:02 UTC, mtsitrin requested changes

2024-02-20 20:02 UTC, mtsitrin commented on go.mod
why it modified?

2024-02-20 20:02 UTC, mtsitrin commented on e2e/go.mod
why it's modified?

2024-02-22 06:45 UTC, muku314115 commented on go.mod
Goland updated some stuff after merging conflicts, reverted the go.mod files to what they were

2024-03-03 19:44 UTC, closed without merging