refactor: add errorlint and make fmt.Errorf use %w to wrap error instead of %v
dymensionxyz/dymension pull request #878
Opened 2024-05-13 01:46 UTC by hoank101

## Description

----

Closes #XXX

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

2024-05-13 08:58 UTC, danwt requested changes

2024-05-13 08:58 UTC, danwt commented on cmd/dymd/cmd/inspect.go
> +				return fmt.Errorf("error exporting state: %w", err)
please remove `error `

2024-05-13 08:58 UTC, danwt commented on cmd/dymd/cmd/inspect.go
> +				return fmt.Errorf("error reading directory: %w", err)
please remove error

2024-05-13 08:58 UTC, danwt requested changes

2024-05-13 08:58 UTC, danwt commented on cmd/dymd/cmd/inspect.go
> +				return fmt.Errorf("error exporting state: %w", err)
```suggestion
				return fmt.Errorf("exporting state: %w", err)
```

2024-05-13 08:58 UTC, danwt commented on cmd/dymd/cmd/inspect.go
> +				return fmt.Errorf("error reading directory: %w", err)
```suggestion
				return fmt.Errorf("reading directory: %w", err)
```

2024-05-13 12:33 UTC, danwt approved these changes
gj!

2024-05-20 13:33 UTC, omritoptix commented
thanks @hoank101. can you please resolve conflicts?

2024-05-20 14:07 UTC, hoank101 commented
> thanks @hoank101. can you please resolve conflicts?

yeah, resolved

2024-05-21 09:10 UTC, danwt commented
@hoank101  you should re-request review if you want review again

2024-05-21 10:27 UTC, mtsitrin approved these changes

2024-05-21 12:09 UTC, merged